// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/content-scripts/content-bridge.js"
    | "/content-scripts/page-provider.js"
    | "/fonts/fonts.css"
    | "/fonts/oxanium-400.woff2"
    | "/fonts/oxanium-600.woff2"
    | "/fonts/sora-400.woff2"
    | "/fonts/sora-600.woff2"
    | "/full-tab.html"
    | "/notification.html"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
