/**
 * abi-registry-gen — turn the synced artifacts in `packages/electroswap/abis`
 * into a committed TypeScript module the security package can import.
 *
 * Why generate into `packages/security` instead of importing the artifacts
 * where they already sit: `@boltvault/electroswap` devDepends on
 * `@boltvault/security`, so a dependency the other way would close a cycle.
 * Copying the bytes under `src/generated` keeps the firewall self-contained
 * and keeps the decoder's ABIs in the same package as the decoder — while the
 * sha256 carried beside each ABI keeps them answerable to the artifact they
 * came from, which is what the drift test checks.
 *
 * Usage: pnpm abi:registry (also run at the end of pnpm abi:sync).
 */
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

interface ManifestEntry {
  readonly source: string
  readonly sha256: string
  readonly functions: number
  readonly events: number
  readonly verifiedAgainst?: string
}

const ABIS = resolve('packages/electroswap/abis')
const OUT = resolve('packages/security/src/generated/abis.ts')

const HEADER = `/**
 * GENERATED by tools/abi-registry-gen.ts — do not edit by hand.
 *
 * Every ABI here is the artifact of a deployed contract, copied from
 * packages/electroswap/abis with the sha256 of the artifact it came from.
 * To change one, change the artifact (pnpm abi:sync) and regenerate; the
 * drift test in packages/security/tests/abi-registry.test.ts fails if this
 * file and the artifacts disagree.
 */
import type { Abi } from 'viem'

export interface ArtifactAbi {
  /** Registry name, matching the key in packages/electroswap/abis/manifest.json. */
  readonly name: string
  /** Where the artifact came from in the ElectroSwap workspace. */
  readonly source: string
  /** sha256 of packages/electroswap/abis/<name>.json as it was when generated. */
  readonly sha256: string
  readonly abi: Abi
}

/*
  Typed as \`readonly unknown[]\` rather than \`Abi\` on the way in: contextually
  checking several thousand object literals against viem's \`Abi\` union costs
  real time on every typecheck and buys nothing, because the artifacts are
  already validated against their manifest hash by the drift test.
*/
interface RawArtifact {
  readonly name: string
  readonly source: string
  readonly sha256: string
  readonly abi: readonly unknown[]
}

`

export function generateRegistry(): void {
  const manifestPath = join(ABIS, 'manifest.json')
  if (!existsSync(manifestPath)) throw new Error(`no manifest at ${manifestPath} — run pnpm abi:sync first`)
  const manifest: Record<string, ManifestEntry> = JSON.parse(readFileSync(manifestPath, 'utf8'))
  const names = Object.keys(manifest).sort()
  if (names.length === 0) throw new Error('manifest is empty')

  const chunks: string[] = []
  for (const name of names) {
    const entry = manifest[name]
    if (!entry) continue
    const path = join(ABIS, `${name}.json`)
    if (!existsSync(path)) throw new Error(`manifest lists ${name} but ${path} is missing`)
    const raw = readFileSync(path, 'utf8')
    const sha256 = createHash('sha256').update(raw).digest('hex')
    // A mismatch here means someone edited an artifact by hand. Say so now, not at runtime.
    if (sha256 !== entry.sha256) throw new Error(`${name}.json does not match the manifest hash (${sha256} vs ${entry.sha256}) — re-run pnpm abi:sync`)
    const abi: unknown = JSON.parse(raw)
    if (!Array.isArray(abi)) throw new Error(`${name}.json is not an ABI array`)
    chunks.push(`  {\n    name: ${JSON.stringify(name)},\n    source: ${JSON.stringify(entry.source)},\n    sha256: ${JSON.stringify(sha256)},\n    abi: ${JSON.stringify(abi)},\n  },`)
  }

  const body = `const RAW: readonly RawArtifact[] = [\n${chunks.join('\n')}\n]\n\nexport const ARTIFACT_ABIS: readonly ArtifactAbi[] = RAW.map((a) => ({ name: a.name, source: a.source, sha256: a.sha256, abi: a.abi as Abi }))\n\nconst BY_NAME = new Map<string, ArtifactAbi>(ARTIFACT_ABIS.map((a) => [a.name, a]))\n\n/** The ABI of a synced artifact. Throws rather than returning an empty ABI, which would decode as "unknown function" forever. */\nexport function artifactAbi(name: string): Abi {\n  const found = BY_NAME.get(name)\n  if (!found) throw new Error(\`no synced artifact named \${name} — run pnpm abi:sync\`)\n  return found.abi\n}\n\n/** The sha256 of the artifact an ABI came from, for the drift test. */\nexport function artifactHash(name: string): string | null {\n  return BY_NAME.get(name)?.sha256 ?? null\n}\n`

  mkdirSync(resolve('packages/security/src/generated'), { recursive: true })
  writeFileSync(OUT, HEADER + body)
  console.log(`generated ${OUT} from ${names.length} artifacts`)
}

if (process.argv[1] && /abi-registry-gen\.ts$/.test(process.argv[1])) generateRegistry()
