/* eslint-disable @typescript-eslint/no-require-imports -- an Expo config plugin is CommonJS */
/**
 * Expo config plugin: the window Android paints before React exists.
 *
 * A cold start used to be three drawings in a row:
 *
 *   1. Android 12's SplashScreen API, which puts the adaptive icon in a 240 dp
 *      circle for a few frames (a small bolt in a circular mask).
 *   2. `AppTheme`'s `windowBackground`, a larger bitmap whose glow was a
 *      square — the PNG was transparent, and the aura died on a Chebyshev
 *      (square) falloff, so the phone showed a plate of light.
 *   3. The JS splash, same large mark, then the rings.
 *
 * Both native beats now paint one object: the same bolt the launcher icon
 * uses (`android-icon-foreground.png` — the mark alone, on transparency, at
 * half scale so it sits in the circular safe zone). No bloom is baked into
 * the bitmap; a glow in a square PNG is a cropped plate of light. 240 dp is
 * Android 12's splash-icon diameter. `SPLASH_MARK` in @boltvault/ui is sized
 * so the polygon is that same bolt when React takes over.
 *
 * `assets/splash-mark.png` is generated by `tools/make-icons.mjs` from the same
 * polygon as the app icon.
 *
 * It is a plugin, not an edit under android/, for the reason `withUsbHost`
 * gives: android/ is gitignored and rewritten by every `expo prebuild`, so an
 * edit there vanishes the next time anyone regenerates the project.
 */
const { withAndroidColors, withAndroidStyles, withAppBuildGradle, withDangerousMod, withMainActivity, AndroidConfig } = require('expo/config-plugins')
const fs = require('node:fs')
const path = require('node:path')

/** paint.void, paint.arc — packages/ui/src/tokens.ts. */
const VOID = '#070A1F'
const ARC = '#4FC3FF'

const COLORS = {
  splashscreen_background: VOID,
  iconBackground: VOID,
  activityBackground: VOID,
  colorPrimary: ARC,
  // `notification_icon_color` is expo-notifications' own — its `color` in
  // app.json is the single source for it, and its plugin wins here anyway.
}

/** Must equal `SPLASH_MARK` in packages/ui/src/SplashArt.tsx. Android 12's splash icon is 240 dp. */
const MARK_DP = 240

const DRAWABLE = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by apps/mobile/plugins/withNativeSplash.js — do not edit; android/ is regenerated. -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
  <item android:drawable="@color/splashscreen_background" />
  <!--
    The size goes on the <item>, not the <bitmap>: android:width/height are not
    <bitmap> attributes and are silently ignored there, so a drawable-nodpi
    asset is drawn at its own pixel size. The item is 240 dp so it matches
    Android 12's splash icon; a larger item was a visible jump from the circle.
  -->
  <item android:gravity="center" android:width="${MARK_DP}dp" android:height="${MARK_DP}dp">
    <bitmap android:src="@drawable/boltvault_splash_mark" android:gravity="center" />
  </item>
</layer-list>
`

/**
 * Adaptive, not a raw bitmap. Android 12 insets a non-adaptive splash icon by
 * a third, which is how a 240 dp mark became "a small bolt in a circular glow"
 * for a few frames. An adaptive icon uses the full 240 dp circle, so the still
 * behind it (the layer-list above) and the icon are the same object.
 *
 * `<adaptive-icon>` is API 26+. It lives in `drawable-v26/`; `drawable/` gets a
 * bitmap of the same name so AAPT is happy at minSdk 24.
 */
const SPLASH_ICON = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by apps/mobile/plugins/withNativeSplash.js — do not edit; android/ is regenerated. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@color/splashscreen_background" />
  <foreground android:drawable="@drawable/boltvault_splash_mark" />
</adaptive-icon>
`

const SPLASH_ICON_PRE26 = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by apps/mobile/plugins/withNativeSplash.js — do not edit; android/ is regenerated. -->
<bitmap xmlns:android="http://schemas.android.com/apk/res/android"
    android:src="@drawable/boltvault_splash_mark"
    android:gravity="center" />
`

/** Window colour for both themes — the still behind the mark. */
const WINDOW = { 'android:windowBackground': '@drawable/boltvault_splash' }

/**
 * Android 12+ SplashScreen API. These belong on the launch theme
 * (`Theme.App.SplashScreen`), not AppTheme: once MainActivity calls
 * `setTheme(AppTheme)` the system splash is already exiting, and the window
 * drawable is what remains.
 *
 * The `android:` names are the platform attributes (API 31+). The bare names
 * are AndroidX's, used if the launch theme's parent is `Theme.SplashScreen`.
 */
const SPLASH_API = {
  windowSplashScreenBackground: '@color/splashscreen_background',
  'android:windowSplashScreenBackground': '@color/splashscreen_background',
  windowSplashScreenAnimatedIcon: '@drawable/boltvault_splash_icon',
  'android:windowSplashScreenAnimatedIcon': '@drawable/boltvault_splash_icon',
  windowSplashScreenIconBackgroundColor: '@color/splashscreen_background',
  'android:windowSplashScreenIconBackgroundColor': '@color/splashscreen_background',
  postSplashScreenTheme: '@style/AppTheme',
}

function withColours(config) {
  return withAndroidColors(config, (c) => {
    for (const [name, value] of Object.entries(COLORS)) {
      c.modResults = AndroidConfig.Colors.assignColorValue(c.modResults, { name, value })
    }
    return c
  })
}

function withSplashDrawable(config) {
  return withDangerousMod(config, [
    'android',
    (c) => {
      const res = path.join(c.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res')
      const drawable = path.join(res, 'drawable')
      const drawableV26 = path.join(res, 'drawable-v26')
      // nodpi: the layer-list gives the bitmap an explicit dp size, so one
      // asset is correct at every density and there are no five copies to keep
      // in step.
      const nodpi = path.join(res, 'drawable-nodpi')
      fs.mkdirSync(drawable, { recursive: true })
      fs.mkdirSync(drawableV26, { recursive: true })
      fs.mkdirSync(nodpi, { recursive: true })
      const mark = path.join(c.modRequest.projectRoot, 'assets', 'splash-mark.png')
      fs.copyFileSync(mark, path.join(nodpi, 'boltvault_splash_mark.png'))
      fs.writeFileSync(path.join(drawable, 'boltvault_splash.xml'), DRAWABLE)
      fs.writeFileSync(path.join(drawable, 'boltvault_splash_icon.xml'), SPLASH_ICON_PRE26)
      fs.writeFileSync(path.join(drawableV26, 'boltvault_splash_icon.xml'), SPLASH_ICON)
      // Expo still generates splashscreen_logo from the app icon. Any leftover
      // reference should paint our mark, not a different bolt.
      for (const dir of fs.readdirSync(res)) {
        if (!dir.startsWith('drawable')) continue
        const logo = path.join(res, dir, 'splashscreen_logo.png')
        if (fs.existsSync(logo)) fs.copyFileSync(mark, logo)
      }
      return c
    },
  ])
}

function upsertStyleItem(style, name, value) {
  style.item = (style.item ?? []).filter((i) => i.$.name !== name)
  style.item.push({ $: { name }, _: value })
}

function withSplashTheme(config) {
  return withAndroidStyles(config, (c) => {
    for (const style of c.modResults.resources.style ?? []) {
      if (style.$.name === 'AppTheme') {
        for (const [name, value] of Object.entries(WINDOW)) upsertStyleItem(style, name, value)
        continue
      }
      if (style.$.name !== 'Theme.App.SplashScreen') continue
      // Keep whatever parent Expo generated (`AppTheme` here). Switching it to
      // `Theme.SplashScreen` would pull in AndroidX's splash theme, which this
      // tree does not ship — expo-splash-screen is not a dependency. The
      // platform `android:windowSplashScreen*` items below are enough on API 31+.
      for (const [name, value] of Object.entries({ ...WINDOW, ...SPLASH_API })) {
        upsertStyleItem(style, name, value)
      }
    }
    return c
  })
}

function withSplashscreenLibrary(config) {
  return withAppBuildGradle(config, (c) => {
    if (c.modResults.contents.includes('androidx.core:core-splashscreen')) return c
    c.modResults.contents = c.modResults.contents.replace(
      /dependencies\s*\{/,
      'dependencies {\n    implementation "androidx.core:core-splashscreen:1.0.1"',
    )
    return c
  })
}

/**
 * Android 12's default splash exit zooms and fades the icon. The activity
 * underneath is the same mark, so that animation reads as a ghost. Pull the
 * splash view as soon as the activity is ready; the still does not move.
 */
function withSplashExit(config) {
  return withMainActivity(config, (c) => {
    let src = c.modResults.contents
    if (src.includes('setOnExitAnimationListener')) return c
    if (!src.includes('androidx.core.splashscreen.SplashScreen')) {
      if (!src.includes('import android.os.Bundle')) {
        console.warn('[withNativeSplash] could not find import android.os.Bundle in MainActivity; splash exit not applied')
        return c
      }
      src = src.replace('import android.os.Bundle', 'import android.os.Bundle\nimport androidx.core.splashscreen.SplashScreen.Companion.installSplashScreen')
    }
    const m = /(\n(\s*)override fun onCreate\(savedInstanceState: Bundle\?\) \{\s*\n)/.exec(src)
    if (!m) {
      console.warn('[withNativeSplash] could not find onCreate in MainActivity; splash exit not applied')
      c.modResults.contents = src
      return c
    }
    const indent = m[2] ?? '    '
    const inner = `${indent}    `
    src = src.replace(m[1], `${m[1]}${inner}installSplashScreen().setOnExitAnimationListener { it.remove() }\n`)
    c.modResults.contents = src
    return c
  })
}

module.exports = function withNativeSplash(config) {
  return withSplashExit(withSplashscreenLibrary(withSplashTheme(withSplashDrawable(withColours(config)))))
}
