/* eslint-disable @typescript-eslint/no-require-imports -- an Expo config plugin is CommonJS */
/**
 * Expo config plugin: stop shipping a 191 MB APK.
 *
 * Owner: "I'd also like to see if we can get the build size down. The apk was
 * ~200mb which seems huge."
 *
 * Measured on the first release build — 221 MB uncompressed, 191 MB packed:
 *
 *   dex, unminified   47.9 MB
 *   lib/x86           44.1 MB
 *   lib/x86_64        43.3 MB
 *   lib/arm64-v8a     41.1 MB
 *   lib/armeabi-v7a   28.2 MB
 *   assets            11.1 MB
 *
 * Almost half of it is x86 and x86_64: emulator architectures that no physical
 * Android phone can execute. librnskia.so alone is ~11 MB and was shipped four
 * times over. Dropping them costs only the ability to run on an x86 emulator —
 * add them back here if you ever need one — and R8 then takes a large bite out
 * of the 47.9 MB of dex.
 *
 * These are gradle.properties values, set from a plugin because android/ is
 * gitignored and regenerated by every prebuild.
 */
const { withAppBuildGradle, withDangerousMod, withGradleProperties } = require('expo/config-plugins')
const fs = require('node:fs')
const path = require('node:path')

/*
  `BOLTVAULT_ABIS` builds for something else — an emulator, in practice.

  A release ships the two ARM slices and nothing more, but every Android
  emulator worth debugging on is x86_64, and an arm64 APK will not install on
  one. Rather than editing this list by hand and forgetting to put it back
  (which is how a build ships for the wrong architecture), the abis are an
  environment variable with the release list as the default:

      BOLTVAULT_ABIS=x86_64 pnpm exec expo prebuild --platform android
      cd android && ./gradlew assembleRelease -PreactNativeArchitectures=x86_64

  It has to be set for the PREBUILD as well as the build: this plugin is what
  writes the list into app/build.gradle.
*/
const ABIS = (process.env.BOLTVAULT_ABIS ?? 'armeabi-v7a,arm64-v8a')
  .split(',')
  .map((a) => a.trim())
  .filter(Boolean)

const PROPERTIES = {
  // The release pair, or whatever BOLTVAULT_ABIS asked for.
  reactNativeArchitectures: ABIS.join(','),
  // R8 over the dex, and drop resources nothing references.
  'android.enableMinifyInReleaseBuilds': 'true',
  'android.enableShrinkResourcesInReleaseBuilds': 'true',
}

/**
 * Turning R8 on surfaced a dependency that cannot exist on Android:
 * @ledgerhq/react-native-hid drags in JNA, whose `Native.getWindowHandle0`
 * references `java.awt.Component`. R8 refuses to finish while a reference is
 * unresolved, so the build failed outright with "Missing class
 * java.awt.Component".
 *
 * JNA is desktop plumbing that the Android transport never calls — the native
 * side goes through Android's own UsbManager — so the AWT reference is
 * genuinely dead. It is silenced rather than kept. JNA's own classes ARE kept:
 * it dispatches by reflection, and a few hundred KB is the wrong thing to
 * gamble a hardware-wallet code path on.
 */
const PROGUARD_RULES = `
# --- BoltVault: added by plugins/withBuildTuning.js ---
# JNA arrives with @ledgerhq/react-native-hid and reaches for desktop AWT,
# which does not exist on Android. The reference is unreachable here.
-dontwarn java.awt.**
-dontwarn com.sun.jna.**
# JNA resolves by reflection, so do not let R8 rename what it looks up.
-keep class com.sun.jna.** { *; }
-keep class * implements com.sun.jna.** { *; }
`

function withProguardRules(config) {
  return withDangerousMod(config, [
    'android',
    (c) => {
      const file = path.join(c.modRequest.platformProjectRoot, 'app', 'proguard-rules.pro')
      const existing = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : ''
      if (!existing.includes('withBuildTuning.js')) fs.writeFileSync(file, existing + PROGUARD_RULES)
      return c
    },
  ])
}

/**
 * One APK per CPU architecture instead of one carrying both.
 *
 * After dropping x86 the build still shipped arm64-v8a (41 MB) and
 * armeabi-v7a (28 MB) to every device, and every device can only execute one
 * of them — so roughly a third of what anyone downloaded was unusable on their
 * phone. Splitting keeps 32-bit support (a Pixel takes the arm64 one, a 2018
 * handset the v7a one) while nobody carries both.
 *
 * `universalApk false` on purpose: a universal APK would put the combined
 * artefact straight back. Gradle writes app-arm64-v8a-release.apk and
 * app-armeabi-v7a-release.apk side by side.
 *
 * For Play, an .aab supersedes this — the store does the same split itself and
 * also splits resources and language assets. This is the sideloading answer.
 */
const SPLITS_BLOCK = `
    splits {
        abi {
            enable true
            reset()
            include ${ABIS.map((a) => `'${a}'`).join(', ')}
            universalApk false
        }
    }
`

function withAbiSplits(config) {
  return withAppBuildGradle(config, (c) => {
    if (c.modResults.contents.includes('splits {')) return c
    // Anchor on the android block's opening line, which the Expo template
    // always emits as `android {`.
    c.modResults.contents = c.modResults.contents.replace(/\nandroid \{\n/, `\nandroid {\n${SPLITS_BLOCK}`)
    return c
  })
}

/**
 * Never let the JS bundle claim to be up to date.
 *
 * This shipped three stale APKs before it was noticed. Gradle decides whether
 * to re-run `createBundleReleaseJsAndAssets` from the inputs it knows about,
 * and in a pnpm workspace the screens live in packages/wallet and packages/ui
 * — symlinked in from outside apps/mobile, and invisible to that check. So a
 * build after changing a shared screen printed
 *
 *     > Task :app:createBundleReleaseJsAndAssets UP-TO-DATE
 *
 * packaged the previous bundle, installed happily, and ran the OLD JavaScript.
 * Every signal was green: the build succeeded, the app launched, no exception
 * was thrown. The only symptom was the fix not being there, which reads exactly
 * like the fix not working — and cost a debugging round on a bug that had
 * already been fixed.
 *
 * The honest trade is to rebundle every release build. It costs about a minute.
 * A wallet that silently ships last week's signing code is not worth a minute.
 *
 * If this is ever narrowed to a real input check, it must cover every workspace
 * package the app imports, not just apps/mobile.
 */
const ALWAYS_BUNDLE = `
tasks.configureEach { task ->
    if (task.name == 'createBundleReleaseJsAndAssets') {
        task.outputs.upToDateWhen { false }
    }
}
`

function withAlwaysBundle(config) {
  return withAppBuildGradle(config, (c) => {
    if (c.modResults.contents.includes('createBundleReleaseJsAndAssets')) return c
    c.modResults.contents = c.modResults.contents + ALWAYS_BUNDLE
    return c
  })
}

module.exports = function withBuildTuning(config) {
  config = withProguardRules(config)
  config = withAlwaysBundle(config)
  config = withAbiSplits(config)
  return withGradleProperties(config, (c) => {
    for (const [key, value] of Object.entries(PROPERTIES)) {
      const existing = c.modResults.find((item) => item.type === 'property' && item.key === key)
      if (existing) existing.value = value
      else c.modResults.push({ type: 'property', key, value })
    }
    return c
  })
}
