/* eslint-disable @typescript-eslint/no-require-imports -- an Expo config plugin is CommonJS */
/**
 * Expo config plugin: the window Android paints before React exists.
 *
 * A cold start, filmed and read frame by frame, was 0.75 s of a **pure white**
 * screen, then 1.4 s of an empty dark one, and only then the app. Both halves
 * come from this file's territory:
 *
 *   - The launch theme (`Theme.App.SplashScreen`) uses
 *     `@drawable/splashscreen_logo` as its `windowBackground`, and the bitmap
 *     Expo generates there is white — 252,252,252 across 1152 px. That is the
 *     white. `splashscreen_background` in colors.xml, which the first attempt
 *     at this fixed, is not even consulted on that path.
 *   - `MainActivity.onCreate` then calls `setTheme(R.style.AppTheme)`, whose
 *     `windowBackground` is the flat `activityBackground`. That is the 1.4 s of
 *     nothing, and it lasts as long as Hermes takes to evaluate the bundle.
 *
 * So both themes get the same drawable: the void, with the BoltVault mark dead
 * centre at exactly the size and position the JS splash puts it
 * (`SPLASH_MARK` in @boltvault/ui). The brand is on screen at 0 ms, it does not
 * move when React finally paints, and the two seconds of native boot stop being
 * a hole in the launch and become the first beat of it.
 *
 * `assets/splash-mark.png` is generated by `tools/make-icons.mjs` from the same
 * polygon as the app icon, so none of these can drift apart.
 *
 * It is a plugin, not an edit under android/, for the reason `withUsbHost`
 * gives: android/ is gitignored and rewritten by every `expo prebuild`, so an
 * edit there vanishes the next time anyone regenerates the project — which is
 * exactly what happened to the first attempt.
 */
const { withAndroidColors, withAndroidStyles, withDangerousMod, AndroidConfig } = require('expo/config-plugins')
const fs = require('node:fs')
const path = require('node:path')

/** paint.void, paint.arc — packages/ui/src/tokens.ts. */
const VOID = '#070A1F'
const ARC = '#4FC3FF'

const COLORS = {
  splashscreen_background: VOID,
  iconBackground: VOID,
  activityBackground: VOID,
  colorPrimary: ARC,
  // `notification_icon_color` is expo-notifications' own — its `color` in
  // app.json is the single source for it, and its plugin wins here anyway.
}

/** Must equal `SPLASH_MARK` in packages/ui/src/SplashArt.tsx. */
const MARK_DP = 340

const DRAWABLE = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by apps/mobile/plugins/withNativeSplash.js — do not edit; android/ is regenerated. -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
  <item android:drawable="@color/splashscreen_background" />
  <!--
    The size goes on the <item>, not the <bitmap>: android:width/height are not
    <bitmap> attributes and are silently ignored there, so a drawable-nodpi
    asset is drawn at its own pixel size — 1024 px, three quarters of a Pixel's
    width, half again bigger than the mark React draws a second later. The jump
    was visible.
  -->
  <item android:gravity="center" android:width="${MARK_DP}dp" android:height="${MARK_DP}dp">
    <bitmap android:src="@drawable/boltvault_splash_mark" android:gravity="center" />
  </item>
</layer-list>
`

function withColours(config) {
  return withAndroidColors(config, (c) => {
    for (const [name, value] of Object.entries(COLORS)) {
      c.modResults = AndroidConfig.Colors.assignColorValue(c.modResults, { name, value })
    }
    return c
  })
}

function withSplashDrawable(config) {
  return withDangerousMod(config, [
    'android',
    (c) => {
      const res = path.join(c.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res')
      const drawable = path.join(res, 'drawable')
      // nodpi: the layer-list gives the bitmap an explicit dp size, so one
      // asset is correct at every density and there are no five copies to keep
      // in step.
      const nodpi = path.join(res, 'drawable-nodpi')
      fs.mkdirSync(drawable, { recursive: true })
      fs.mkdirSync(nodpi, { recursive: true })
      fs.copyFileSync(path.join(c.modRequest.projectRoot, 'assets', 'splash-mark.png'), path.join(nodpi, 'boltvault_splash_mark.png'))
      fs.writeFileSync(path.join(drawable, 'boltvault_splash.xml'), DRAWABLE)
      return c
    },
  ])
}

function withSplashTheme(config) {
  return withAndroidStyles(config, (c) => {
    for (const style of c.modResults.resources.style ?? []) {
      if (style.$.name !== 'AppTheme' && style.$.name !== 'Theme.App.SplashScreen') continue
      style.item = (style.item ?? []).filter((i) => i.$.name !== 'android:windowBackground')
      style.item.push({ $: { name: 'android:windowBackground' }, _: '@drawable/boltvault_splash' })
    }
    return c
  })
}

module.exports = function withNativeSplash(config) {
  return withSplashTheme(withSplashDrawable(withColours(config)))
}
