/* eslint-disable @typescript-eslint/no-require-imports -- an Expo config plugin is CommonJS */
/**
 * Expo config plugin (master plan §7.13): registers the Android Glance widget
 * receiver and copies the native sources in apps/mobile/native/android into the
 * prebuilt project. Runs at `expo prebuild` (EAS); nothing here touches the JS
 * bundle.
 *
 * Android only, and deliberately so. The iOS WidgetKit + Live Activity target
 * is generated by @bacons/apple-targets, which reads
 * apps/mobile/targets/widget/ — a job this plugin cannot do, because a
 * WidgetKit extension is a second Xcode target with its own product, Info.plist
 * and signing, not a file copied into the app's. That plugin is NOT yet a
 * dependency and NOT yet listed in app.json, so today `expo prebuild -p ios`
 * produces no widget target at all; the CI mobile job fails a release ref while
 * that is true. See native/README.md for the two steps outstanding.
 */
const { withAndroidManifest, withDangerousMod } = require('expo/config-plugins')
const fs = require('node:fs')
const path = require('node:path')

function withAndroidWidget(config) {
  config = withAndroidManifest(config, (c) => {
    const app = c.modResults.manifest.application?.[0]
    if (!app) return c
    app.receiver = app.receiver ?? []
    if (
      !app.receiver.some(
        (r) => r.$['android:name'] === 'io.electroswap.boltvault.widget.BoltVaultWidgetReceiver',
      )
    ) {
      app.receiver.push({
        $: {
          'android:name': 'io.electroswap.boltvault.widget.BoltVaultWidgetReceiver',
          'android:exported': 'true',
          'android:label': 'BoltVault',
        },
        'intent-filter': [
          { action: [{ $: { 'android:name': 'android.appwidget.action.APPWIDGET_UPDATE' } }] },
        ],
        'meta-data': [
          {
            $: {
              'android:name': 'android.appwidget.provider',
              'android:resource': '@xml/boltvault_widget_info',
            },
          },
        ],
      })
    }
    return c
  })
  config = withDangerousMod(config, [
    'android',
    (c) => {
      const root = c.modRequest.platformProjectRoot
      const src = path.join(c.modRequest.projectRoot, 'native', 'android', 'widget')
      const dstKt = path.join(
        root,
        'app',
        'src',
        'main',
        'java',
        'io',
        'electroswap',
        'boltvault',
        'widget',
      )
      fs.mkdirSync(dstKt, { recursive: true })
      fs.copyFileSync(path.join(src, 'BoltVaultWidget.kt'), path.join(dstKt, 'BoltVaultWidget.kt'))
      const xml = path.join(root, 'app', 'src', 'main', 'res', 'xml')
      fs.mkdirSync(xml, { recursive: true })
      fs.copyFileSync(
        path.join(src, 'boltvault_widget_info.xml'),
        path.join(xml, 'boltvault_widget_info.xml'),
      )
      // Glance dependency for the app module.
      const gradle = path.join(root, 'app', 'build.gradle')
      const text = fs.readFileSync(gradle, 'utf8')
      if (!text.includes('androidx.glance:glance-appwidget'))
        fs.writeFileSync(
          gradle,
          text.replace(
            /dependencies\s*\{/,
            'dependencies {\n    implementation("androidx.glance:glance-appwidget:1.1.1")\n    implementation("androidx.glance:glance-material3:1.1.1")',
          ),
        )
      return c
    },
  ])
  return config
}

module.exports = function withWidgets(config) {
  return withAndroidWidget(config)
}
