/**
 * ATT-BV-008 — a release APK is signed with a release key, or the build stops.
 *
 * The Expo template gives `release` the debug signing config, and the debug
 * key ships with the SDK. Android treats the signature as the upgrade
 * identity, so a debug-signed install accepts an "update" from anybody: same
 * UID, same files, same Keystore entries — the device wrap key and the MMKV
 * secret-store key among them. `android/` is gitignored and regenerated by
 * every prebuild, so what is pinned here is the edit the plugin makes, against
 * the template's own shape.
 */
import { describe, expect, it } from 'vitest'
import { createRequire } from 'node:module'

const require_ = createRequire(import.meta.url)
const { applyToBuildGradle } = require_('../plugins/withReleaseSigning.js') as { applyToBuildGradle: (s: string) => string }

/** The relevant lines of what `expo prebuild` writes, verbatim in shape. */
const TEMPLATE = `
apply plugin: "com.android.application"

android {
    namespace 'io.electroswap.boltvault'
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            signingConfig signingConfigs.debug
            shrinkResources true
            minifyEnabled true
        }
    }
}
`

describe('the release signing config', () => {
  const out = applyToBuildGradle(TEMPLATE)

  it('takes the release build type off the debug key when there is a release key', () => {
    const buildTypes = out.slice(out.indexOf('buildTypes {'))
    expect(buildTypes).toContain('signingConfigs.boltvaultRelease')
    // The debug build type keeps its own key; only `release` moves.
    expect(buildTypes.split('release {')[0]).toContain('signingConfig signingConfigs.debug')
  })

  /*
    The escape hatch has to produce a signable APK, not a different failure.

    `BOLTVAULT_ALLOW_DEBUG_SIGNED_RELEASE=1` used to get past the guard and then
    die in `packageRelease` with `SigningConfig "boltvaultRelease" is missing
    required property "storeFile"` — the config was left half-built, because the
    branch that set a keystore and the branch that set `storeFile null` both
    declined to run. Nothing selects that config now: the build type chooses
    between the release key and the SDK's own debug config, and choosing is what
    makes "signed with the debug key" an outcome rather than an error.
  */
  it('lets the release build type fall back to the SDK debug config, and leaves it whole', () => {
    const buildTypes = out.slice(out.indexOf('buildTypes {'))
    const release = buildTypes.slice(buildTypes.indexOf('release {'))
    expect(release).toContain('signingConfigs.debug')
    expect(release).toContain("System.getenv('BOLTVAULT_RELEASE_KEYSTORE')")
    // A config that is never fully built must never be the one selected.
    expect(out).not.toContain('storeFile null')
  })

  it('reads the keystore and its passwords from the environment, never the repo', () => {
    expect(out).toContain("System.getenv('BOLTVAULT_RELEASE_KEYSTORE')")
    expect(out).toContain("System.getenv('BOLTVAULT_RELEASE_KEYSTORE_PASSWORD')")
    expect(out).toContain("System.getenv('BOLTVAULT_RELEASE_KEY_ALIAS')")
    expect(out).toContain("System.getenv('BOLTVAULT_RELEASE_KEY_PASSWORD')")
    // Nothing that looks like a secret is written into the build file.
    expect(out).not.toMatch(/storePassword\s+["']/)
  })

  it('fails the build rather than falling back, unless the fallback is asked for out loud', () => {
    expect(out).toContain('throw new GradleException')
    expect(out).toContain('BOLTVAULT_ALLOW_DEBUG_SIGNED_RELEASE')
  })

  it('is idempotent, because prebuild runs more than once', () => {
    expect(applyToBuildGradle(out)).toBe(out)
  })
})
